### ISSUE TITLE
Создание серверной части по запуску ботов

### ISSUE THREAD

**Issue by olees-orlenko** [modular-platform-it/backend#30]
Реализация фукционала по запуску ботов, которые были созданы в приложении управления.

1) Получать по API управляющие команды и отправлять их на Django интерфейс
2) Создавать экземпляр готового бота:
1 вариант) на основе нескольких классов, представляющие себя детей основного класса BasicBot.
2 вариант) на основе списка действий, где будет храниться методы класса BasicBot с необходимыми данными
3) Созданные экземпляры должны храниться в БД в виде ключ значения Reddis
4) Асинхронно запускать бота на основе данных из БД: Сервер очередей
5) Опрашивать Бота о его состоянии
6) Бот должен уметь отправлять запросы по API к сторонним сервисам

**Comment by olees-orlenko** [comment]
Реализация фукционала по запуску ботов, которые были созданы в приложении управления

**Comment by Paymir121** [comment]
1) Создать fastapi с  гет запросом самым простым, принимающий параметры бота
2) перенести poetry в приложение
3 ) Конфигурацию можно сделать с помощью списка словарей, содержащий название метода и параметры. При создании экземпляра конфигурация будет происходить проходом циклом по этому списке и асинхроно выполняя методы getattr(self, method_name)(**parameters), примерно так
4) Создать докерфайл
5) Подключение БД и запуск нескольких ботов
