### ISSUE TITLE
Запуск нескольких ботов

### ISSUE THREAD

**Issue by olees-orlenko** [modular-platform-it/backend#9]
Изучение информации по запуску нескольких ботов (асинхронно).

**Comment by Geroy4ik** [comment]
Никто не рассматривал вариант с webhook'ами?
При "запуске" бота,  будет отсылаться команда на регистрацию нового вебхука типа www.exaple.org/tg_hooks/{id бота}/hook?.
На входе будет что-нибудь для очереди запросов(Celery + Redis?).
Из минусов:
-  надо настроить для домена сертификат TLS кажется
-  если телеграм придет с проверкой webhook'а, а наш сервер будет лежать или логика не сработает, то получим бан для бота
- регистрация нового webhook'а может занять какое-то время

**Comment by olees-orlenko** [comment]
1. **Выбор асинхронного фреймворка**: В Python есть несколько фреймворков для асинхронного программирования, но наиболее популярным и широко используемым является asyncio. Он включен в стандартную библиотеку Python и предоставляет мощные инструменты для создания асинхронных приложений.

2. **Реализация ботов**: Реализуйте каждого бота в виде асинхронной функции или класса, используя асинхронные библиотеки для взаимодействия с внешними сервисами, такими как API социальных сетей или веб-сайтов.

3. **Управление ботами**: Используйте возможности asyncio для управления запуском, выполнением и остановкой ботов. Это может включать создание корутин (асинхронных функций), запуск их с помощью asyncio.run() или asyncio.create_task(), и использование механизмов синхронизации, таких как asyncio.Event или asyncio.Queue, для управления потоком выполнения.

4. **Масштабирование**: Если количество ботов становится очень большим и вы хотите распределить нагрузку между несколькими процессами или даже машинами, вы можете рассмотреть использование очередей сообщений, таких как RabbitMQ или Apache Kafka, в сочетании с асинхронными библиотеками, такими как aiormq или aiokafka, для асинхронной обработки сообщений.

Вот пример того, как можно использовать asyncio для одновременного запуска нескольких ботов:
import asyncio

async def bot1():
    while True:
        print("Bot 1 is running...")
        await asyncio.sleep(1)

async def bot2():
    while True:
        print("Bot 2 is running...")
        await asyncio.sleep(1)

async def main():
    # Запуск ботов в виде задач
    task1 = asyncio.create_task(bot1())
    task2 = asyncio.create_task(bot2())

    # Ожидание завершения всех задач
    await task1
    await task2

asyncio.run(main())
